@url = https://8080-mikeeeevale-gamessw2202-e0cb0avthnh.ws-us116.gitpod.io

GET {{url}}/jogos

###
POST {{url}}/jogos
Content-Type: application/json

{
    "titulo": "Vampire Survivors",
    "plataformas": [
        {"id": 1},
        {"id":2}
    ]
}

###
DELETE {{url}}/jogos/5

###
PUT {{url}}/jogos/5
Content-Type: application/json

{
    "titulo": "Vampire Survivors - alterado",
    "plataformas": [
        {"id": 2}
    ]
}